#!/bin/bash
echo "Essential configuration installer"

echo "👉 Updating packages"
sudo apt-get update -y > /dev/null

echo "👉 Install GIT ZSH and VIM CURL"
sudo apt-get install git zsh vim curl -y > /dev/null

echo "👉 Change default terminal to ZSH"
chsh -s $(which zsh) > /dev/null

echo "👉 Change default terminal to ZSH"
npm install -g yarn > /dev/null

echo "👉 Install Konsole"
sudo apt-get install konsole -y > /dev/null

echo "👉 Installing docker"
case $(uname | tr '[:upper:]' '[:lower:]') in
  linux*)
    sudo apt-get update > /dev/null

    sudo apt-get install \
        ca-certificates \
        curl \
        gnupg \
        lsb-release -y > /dev/null

    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update > /dev/null
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y > /dev/null

    sudo groupadd docker
    sudo usermod -aG docker $USER
    ;;
  *)
    echo "Please refer to the official documentation for your Operating System: https://docs.docker.com/desktop/"
    echo -n "Would you like to proceed with the next steps? (y/n)"
    read reply

    if [ "$reply" = n -o "$reply" = N ]
    then
       exit
    fi
    ;;
esac

#install MKCERT > 
# sudo apt install libnss3-tools REQUIRED
# BREW REQUIRED 
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# brew install mkcert

echo "👉  Cloning nvm into: ${HOME}/.nvm"
git clone https://github.com/nvm-sh/nvm.git "${HOME}/.nvm" 2> /dev/null || git -C "${HOME}/.nvm" checkout `git -C "${HOME}/.nvm" describe --abbrev=0 --tags --match "v[0-9]*" $(git -C "${HOME}/.nvm" rev-list --tags --max-count=1)`

# ^
#Forgot to install a nvm version at least

echo "👉  Cloning prezto into: ${HOME}/.zprezto"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${HOME}/.zprezto" 2> /dev/null || git -C "${HOME}/.zprezto" pull

echo "👉 Cloning Vundle into: ${HOME}/.vim/bundle/Vundle.vim"
git clone https://github.com/VundleVim/Vundle.vim.git "${HOME}/.vim/bundle/Vundle.vim"